[package]
name = "svoyak_bot"
version = "0.1.0"
authors = ["stash <stash@fb.com>"]

[dependencies]
failure = "*"
futures = "*"
telegram-bot = "*"
tokio-core = "*"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
